### ISSUE TITLE
Code error in h_eurynd.d

### ISSUE THREAD

**Issue by vanimmaus** [TotalMilk90/gorgon#4]
BEGIN h_eurynd

IF ~True()~ THEN BEGIN 0
   SAY @4200 IF ~~ THEN EXIT
       ++ @4201 GOTO STORE_1
       ++ @4202 EXIT
       ++ @4203 GOTO UPGRADE_1
       +~Global("h_GuildItems","GLOBAL",1)~+ @4204 GOTO ARMOR_2
       +~PartyHasItem("h_misc03")~+ @4205 GOTO KERY_1
END

It should be THEN DO instead of THEN EXIT. The dlg is running, but the dialog options are named 2-4 and not 1-3. No big deal but I would recommend to fix it.

**Comment by TotalMilk90** [comment]
Nice find, thank you! I can't believe I missed that, I always wondered why that listed as 2-4 but I couldn't figure it out. I'll fix it in the next 3.2 release.
